### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for Config

### ISSUE THREAD

**Issue by RokasUrbelis** [chrisyy2003/nonebot-plugin-gpt3#28]
02-25 16:12:14 [ERROR] nonebot | Failed to import "nonebot_plugin_gpt3"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/opt/openai-bot/.venv/lib/python3.9/site-packages/nonebot/plugin/load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/opt/openai-bot/.venv/lib/python3.9/site-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "/opt/openai-bot/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/opt/openai-bot/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/opt/openai-bot/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/opt/openai-bot/.venv/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/openai-bot/.venv/lib/python3.9/site-packages/nonebot_plugin_gpt3/__init__.py", line 10, in <module>
    from .config import *
  File "/opt/openai-bot/.venv/lib/python3.9/site-packages/nonebot_plugin_gpt3/config.py", line 24, in <module>
    config = Config.parse_obj(global_config)
  File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
    return cls(**obj)
  File "pydantic/env_settings.py", line 39, in pydantic.env_settings.BaseSettings.__init__
    super().__init__(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Config
gpt3_api_key_list_from_env
  value is not a valid list (type=type_error.list)
![image](https://user-images.githubusercontent.com/48517501/221346605-ffc90661-c6f9-4b97-832b-28e1f2d44cb1.png)
 
**系统环境&软件版本：Python3.9、Debian11、NoneBot2**

**Comment by chrisyy2003** [comment]
[daf35cf](https://github.com/chrisyy2003/nonebot-plugin-gpt3/commit/daf35cfbda360b5114799d4e8ba99f40c3cfcacb) fix
